### ISSUE TITLE
Error while setting-up

### ISSUE THREAD

**Issue by duezerouno** [interpunkt/generator-craftskeleton#1]
Hi! just playing with your generator and it throws me this error

```
? Tell me the name of this project Pallars
? Would you like to download the latest Craft CMS? Yes
? [LOCAL] Domain of your local installation pallars.dev
? [LOCAL] Name of your local database server localhost
? [LOCAL] Name of your local database user root
? [LOCAL] Password of your local database user root
? [LOCAL] Name of your local database pallars
? [STAGE] Domain of your stage installation
? [STAGE] Name of your stage database server
? [STAGE] Name of your stage database user
? [STAGE] Password of your stage database user
? [STAGE] Name of your stage database
```

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn wget ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
I am not a dev, any idea how could I solve this? Cheers

**Comment by vonsio** [comment]
Hi @duezerouno 

You have to install [wget](https://www.hacksparrow.com/how-to-install-wget-on-your-mac.html), because the generator downloads the current version of craftcms with wget.

Let me know if you have further questions.

**Comment by duezerouno** [comment]
@slimiles thank you! 👍

**Comment by duezerouno** [comment]
@slimiles thank you! 👍

**Comment by benblub** [comment]
WGET for Windows, would be nice adding to Readme as Requirement for Windows Users..
http://gnuwin32.sourceforge.net/packages/wget.htm

**Comment by vonsio** [comment]
@benblub Updated the README for wget in the last commit ([8298ff5](https://github.com/interpunkt/generator-craftskeleton/commit/8298ff580c7bb1ffbb82b680dbbd8dbc10245058)).
